export const ADD_USER = 'ADD_USER';

export const TESTS_LOADING = 'TESTS_LOADING';
export const TESTS_FAILED = 'TESTS_FAILED';
export const ADD_TESTS = 'ADD_TESTS';

export const SECTIONS_LOADING = 'SECTIONS_LOADING';
export const SECTIONS_FAILED = 'SECTIONS_FAILED';
export const ADD_SECTIONS = 'ADD_SECTIONS';

export const TOPIC_LOADING = 'TOPIC_LOADING';
export const TOPIC_FAILED = 'TOPIC_FAILED';
export const ADD_TOPIC = 'ADD_TOPIC';

export const QUIZ_LOADING = 'QUIZ_LOADING';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const QUIZ_FAILED = 'QUIZ_FAILED';
export const SET_VISITED_QUESTIONS = 'SET_VISITED_QUESTIONS';
export const SET_ANSWERED_QUESTIONS = 'SET_ANSWERED_QUESTIONS';
export const SET_YOUR_ANSWERS = 'SET_YOUR_ANSWERS';
export const UPDATE_VISITED_QUESTIONS = 'UPDATE_VISITED_QUESTIONS';
export const UPDATE_ANSWERED_QUESTIONS = 'UPDATE_ANSWERED_QUESTIONS';
export const UPDATE_YOUR_ANSWERS = 'UPDATE_YOUR_ANSWERS';
export const UPDATE_ACTIVE_QUESTION = 'UPDATE_ACTIVE_QUESTION';

export const RESULT_LOADING = 'RESULT_LOADING';
export const ADD_RESULT_CLASS = 'ADD_RESULT_CLASS';
export const ADD_RESULT_SCORE = 'ADD_RESULT_SCORE';






